apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: scraper-image:latest
          ports:
            - containerPort: 5314
          volumeMounts:
            - name: scraper-storage
              mountPath: /usr/src/app/data
      volumes:
        - name: scraper-storage
          persistentVolumeClaim:
            claimName: scraper-pvc
